import { useState, useRef, useEffect } from 'react';
import { 
  FileText, Video, Download, Eye, BookOpen, X,
  Search, Play, Pause, Volume2, VolumeX, 
  MessageCircle, Send, Sparkles, Brain, Lightbulb,
  BookmarkPlus, Highlighter, Share2, Clock, Zap,
  ChevronRight, CheckCircle, Star, Target, AlertCircle,
  Headphones, SkipForward, SkipBack, Settings, Maximize,
  FileQuestion, ListChecks, Map, PenTool, Trophy, Flame
} from 'lucide-react';

interface InteractiveStudyMaterialProps {
  materialId: number;
  materialType: 'video' | 'notes' | 'audio';
  title: string;
  subject: string;
  onClose: () => void;
}

interface ChatMessage {
  id: string;
  role: 'student' | 'ai';
  content: string;
  timestamp: Date;
  context?: string; // timestamp for video, paragraph for notes
}

interface Annotation {
  id: string;
  text: string;
  timestamp?: number; // for video/audio
  paragraph?: number; // for notes
  note: string;
  color: string;
}

interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export function InteractiveStudyMaterial({ 
  materialId, 
  materialType, 
  title, 
  subject,
  onClose 
}: InteractiveStudyMaterialProps) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Playback state
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [volume, setVolume] = useState(1);
  const [isMuted, setIsMuted] = useState(false);
  const [playbackSpeed, setPlaybackSpeed] = useState(1);

  // AI Tutor state
  const [showAITutor, setShowAITutor] = useState(true);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      role: 'ai',
      content: `👋 Hi! I'm your AI Study Tutor. I'm here to help you understand "${title}"!\n\n📚 You can:\n• Ask questions about the content\n• Request explanations of concepts\n• Get practice problems\n• Ask for summaries\n• Request related examples\n\nJust type your question or select a quick action below! 🎓`,
      timestamp: new Date()
    }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);

  // Interactive features state
  const [annotations, setAnnotations] = useState<Annotation[]>([]);
  const [showAnnotations, setShowAnnotations] = useState(true);
  const [highlightedText, setHighlightedText] = useState('');
  const [showQuickActions, setShowQuickActions] = useState(true);
  const [autoGeneratedQuiz, setAutoGeneratedQuiz] = useState<QuizQuestion[]>([]);
  const [showQuiz, setShowQuiz] = useState(false);
  const [currentQuizIndex, setCurrentQuizIndex] = useState(0);
  const [quizAnswers, setQuizAnswers] = useState<number[]>([]);

  // Notes content (sample)
  const notesContent = `
# ${title}

## Introduction
${subject} is a fundamental subject in competitive examinations. This comprehensive study material covers all essential concepts with detailed explanations and examples.

## Key Concepts

### Concept 1: Fundamental Principles
The fundamental principles of ${subject} include several important aspects that form the foundation of advanced topics. Understanding these basics is crucial for solving complex problems.

**Important Points:**
- Point 1: Core principle explanation
- Point 2: Application in problem solving
- Point 3: Common mistakes to avoid

### Concept 2: Advanced Applications
Building upon the fundamentals, we explore advanced applications that frequently appear in competitive exams.

**Formula:** 
\`E = mc²\` (Example formula)

**Example Problem:**
Given the conditions, calculate the result using the formula above.

**Solution:**
Step 1: Identify variables
Step 2: Apply formula
Step 3: Calculate result

### Concept 3: Problem-Solving Strategies
Effective problem-solving requires a systematic approach:
1. Understand the problem
2. Identify given information
3. Choose appropriate method
4. Execute calculation
5. Verify result

## Practice Questions
Try these questions to test your understanding:
1. Question about fundamental concept
2. Application-based question
3. Complex problem requiring multiple steps

## Summary
This material covered key concepts in ${subject}. Regular practice and understanding of fundamentals will ensure success in competitive exams.
  `.trim();

  // Sample quiz questions
  useEffect(() => {
    // Auto-generate quiz based on material
    const sampleQuiz: QuizQuestion[] = [
      {
        id: 1,
        question: `What is the fundamental principle discussed in ${title}?`,
        options: [
          'Option A: Basic concept explanation',
          'Option B: Advanced application',
          'Option C: Problem-solving strategy',
          'Option D: Summary points'
        ],
        correctAnswer: 0,
        explanation: 'The fundamental principle is explained in the introduction section, covering basic concepts.'
      },
      {
        id: 2,
        question: 'Which formula is used for calculating energy?',
        options: [
          'E = mv',
          'E = mc²',
          'E = mgh',
          'E = ½mv²'
        ],
        correctAnswer: 1,
        explanation: 'E = mc² is the famous Einstein equation for mass-energy equivalence.'
      },
      {
        id: 3,
        question: 'What is the first step in problem-solving?',
        options: [
          'Calculate result',
          'Apply formula',
          'Understand the problem',
          'Verify result'
        ],
        correctAnswer: 2,
        explanation: 'Understanding the problem is always the first step in any problem-solving approach.'
      }
    ];
    setAutoGeneratedQuiz(sampleQuiz);
  }, [title]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  // Playback controls
  const togglePlayPause = () => {
    if (materialType === 'video' && videoRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
      } else {
        videoRef.current.play();
      }
      setIsPlaying(!isPlaying);
    } else if (materialType === 'audio' && audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
      } else {
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  const handleTimeUpdate = () => {
    if (materialType === 'video' && videoRef.current) {
      setCurrentTime(videoRef.current.currentTime);
    } else if (materialType === 'audio' && audioRef.current) {
      setCurrentTime(audioRef.current.currentTime);
    }
  };

  const handleLoadedMetadata = () => {
    if (materialType === 'video' && videoRef.current) {
      setDuration(videoRef.current.duration);
    } else if (materialType === 'audio' && audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const seekTo = (time: number) => {
    if (materialType === 'video' && videoRef.current) {
      videoRef.current.currentTime = time;
    } else if (materialType === 'audio' && audioRef.current) {
      audioRef.current.currentTime = time;
    }
    setCurrentTime(time);
  };

  const skip = (seconds: number) => {
    const newTime = Math.max(0, Math.min(currentTime + seconds, duration));
    seekTo(newTime);
  };

  const toggleMute = () => {
    if (materialType === 'video' && videoRef.current) {
      videoRef.current.muted = !isMuted;
    } else if (materialType === 'audio' && audioRef.current) {
      audioRef.current.muted = !isMuted;
    }
    setIsMuted(!isMuted);
  };

  const changeSpeed = (speed: number) => {
    if (materialType === 'video' && videoRef.current) {
      videoRef.current.playbackRate = speed;
    } else if (materialType === 'audio' && audioRef.current) {
      audioRef.current.playbackRate = speed;
    }
    setPlaybackSpeed(speed);
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // AI Chat functions
  const handleSendMessage = () => {
    if (!chatInput.trim()) return;

    const context = materialType === 'video' || materialType === 'audio' 
      ? `at ${formatTime(currentTime)}` 
      : 'in notes';

    const studentMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'student',
      content: chatInput,
      timestamp: new Date(),
      context
    };

    setChatMessages([...chatMessages, studentMessage]);
    setChatInput('');
    setIsTyping(true);

    // Simulate AI response
    setTimeout(() => {
      const response = generateAIResponse(chatInput.toLowerCase(), context);
      const aiMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: 'ai',
        content: response,
        timestamp: new Date()
      };
      setChatMessages(prev => [...prev, aiMessage]);
      setIsTyping(false);
    }, 1500);
  };

  const generateAIResponse = (question: string, context: string): string => {
    // Context-aware AI responses
    if (question.includes('explain') || question.includes('what is')) {
      return `Great question! Let me explain this concept:\n\n**Concept Explanation:**\nBased on what you're studying ${context}, this topic relates to fundamental principles in ${subject}.\n\n**Key Points:**\n• The core idea is...\n• This connects to...\n• Important applications include...\n\n**Example:**\nImagine a scenario where...\n\nDoes this help clarify? Feel free to ask follow-up questions! 🎓`;
    } else if (question.includes('example') || question.includes('problem')) {
      return `📝 **Practice Problem:**\n\nLet me give you a relevant example ${context}:\n\n**Problem:**\nCalculate the result given these conditions...\n\n**Solution Approach:**\n1. Identify what's given\n2. Choose the right formula\n3. Substitute values\n4. Calculate step by step\n\n**Answer:** [Result]\n\nWant to try solving a similar problem? 🎯`;
    } else if (question.includes('formula') || question.includes('equation')) {
      return `🔢 **Important Formulas:**\n\nFor this topic ${context}, here are the key formulas:\n\n1. **Main Formula:** E = mc²\n   - Use when: calculating energy\n   - Variables: m (mass), c (speed of light)\n\n2. **Derived Formula:** ...\n\n**Pro Tip:** Remember these formulas by understanding their derivation! 💡`;
    } else if (question.includes('summary') || question.includes('summarize')) {
      return `📚 **Quick Summary** ${context}:\n\n**Main Points:**\n✓ Concept 1: Fundamental principles\n✓ Concept 2: Applications\n✓ Concept 3: Problem-solving\n\n**Key Takeaways:**\n• Understanding basics is crucial\n• Practice problems regularly\n• Connect concepts together\n\n**Next Steps:**\nTry the auto-generated quiz to test your understanding! 🎯`;
    } else if (question.includes('difficult') || question.includes('hard') || question.includes('confused')) {
      return `I understand this can be challenging! Let's break it down:\n\n**Simplified Explanation:**\nThink of it this way... ${context}\n\n**Common Mistakes:**\n❌ Don't confuse X with Y\n❌ Remember to check units\n✅ Always verify your answer\n\n**Helpful Analogy:**\nIt's like... (real-world example)\n\nWould you like me to explain any specific part? 🤔`;
    } else if (question.includes('quiz') || question.includes('test') || question.includes('practice')) {
      return `🎯 **Ready to Practice?**\n\nI can help you with:\n1. Auto-generated quiz (3 questions)\n2. Practice problems\n3. Previous year questions\n4. Concept-based MCQs\n\nClick the "Take Quiz" button to start! You can also ask me for specific practice problems. 📝`;
    } else {
      return `Interesting question ${context}! 🤔\n\nFor ${subject}, this relates to the concepts we're studying. Let me help:\n\n**Answer:**\nThe key point here is that... [explanation]\n\n**Related Topics:**\n• Topic 1\n• Topic 2\n• Topic 3\n\n**Want to Know More?**\nI can:\n- Explain with examples\n- Show you formulas\n- Give practice problems\n- Create a mind map\n\nWhat would help you most? 💡`;
    }
  };

  const handleQuickAction = (action: string) => {
    setChatInput(action);
    setTimeout(() => handleSendMessage(), 100);
  };

  const addAnnotation = () => {
    if (!highlightedText) return;

    const newAnnotation: Annotation = {
      id: Date.now().toString(),
      text: highlightedText,
      timestamp: materialType !== 'notes' ? currentTime : undefined,
      note: '',
      color: '#FCD34D'
    };

    setAnnotations([...annotations, newAnnotation]);
    setHighlightedText('');
  };

  const renderQuiz = () => {
    if (autoGeneratedQuiz.length === 0) return null;

    const currentQ = autoGeneratedQuiz[currentQuizIndex];
    const hasAnswered = quizAnswers[currentQuizIndex] !== undefined;

    return (
      <div className="bg-white rounded-lg shadow-lg p-6 border-2 border-purple-200">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-bold text-purple-900">
            📝 Auto-Generated Quiz
          </h3>
          <button
            onClick={() => setShowQuiz(false)}
            className="text-gray-400 hover:text-gray-600"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="mb-4">
          <div className="flex justify-between text-sm text-gray-600 mb-2">
            <span>Question {currentQuizIndex + 1} of {autoGeneratedQuiz.length}</span>
            <span>{Math.round((quizAnswers.filter(a => a !== undefined).length / autoGeneratedQuiz.length) * 100)}% Complete</span>
          </div>
          <div className="w-full bg-gray-200 rounded-full h-2">
            <div 
              className="bg-purple-500 h-2 rounded-full transition-all"
              style={{ width: `${(quizAnswers.filter(a => a !== undefined).length / autoGeneratedQuiz.length) * 100}%` }}
            />
          </div>
        </div>

        <div className="bg-purple-50 p-4 rounded-lg mb-4">
          <p className="text-gray-800 font-bold mb-3">{currentQ.question}</p>
          <div className="space-y-2">
            {currentQ.options.map((option, idx) => (
              <button
                key={idx}
                onClick={() => {
                  if (!hasAnswered) {
                    const newAnswers = [...quizAnswers];
                    newAnswers[currentQuizIndex] = idx;
                    setQuizAnswers(newAnswers);
                  }
                }}
                disabled={hasAnswered}
                className={`w-full text-left px-4 py-3 rounded-lg border-2 transition-all ${
                  hasAnswered
                    ? idx === currentQ.correctAnswer
                      ? 'bg-green-100 border-green-500 text-green-800'
                      : idx === quizAnswers[currentQuizIndex]
                      ? 'bg-red-100 border-red-500 text-red-800'
                      : 'bg-white border-gray-200 text-gray-500'
                    : 'bg-white border-gray-300 hover:border-purple-500 hover:bg-purple-50'
                }`}
              >
                {option}
                {hasAnswered && idx === currentQ.correctAnswer && (
                  <CheckCircle className="inline ml-2 w-5 h-5 text-green-600" />
                )}
              </button>
            ))}
          </div>
        </div>

        {hasAnswered && (
          <div className="bg-blue-50 border-2 border-blue-200 p-4 rounded-lg mb-4">
            <p className="text-sm text-blue-900">
              <strong>Explanation:</strong> {currentQ.explanation}
            </p>
          </div>
        )}

        <div className="flex gap-2">
          {currentQuizIndex > 0 && (
            <button
              onClick={() => setCurrentQuizIndex(currentQuizIndex - 1)}
              className="px-4 py-2 bg-gray-200 hover:bg-gray-300 rounded-lg font-bold text-sm"
            >
              Previous
            </button>
          )}
          {currentQuizIndex < autoGeneratedQuiz.length - 1 && (
            <button
              onClick={() => setCurrentQuizIndex(currentQuizIndex + 1)}
              className="flex-1 px-4 py-2 bg-purple-500 hover:bg-purple-600 text-white rounded-lg font-bold text-sm"
            >
              Next Question
            </button>
          )}
          {currentQuizIndex === autoGeneratedQuiz.length - 1 && (
            <button
              onClick={() => {
                const score = quizAnswers.reduce((acc, ans, idx) => {
                  return acc + (ans === autoGeneratedQuiz[idx].correctAnswer ? 1 : 0);
                }, 0);
                alert(`Quiz Complete! Score: ${score}/${autoGeneratedQuiz.length}`);
                setShowQuiz(false);
              }}
              className="flex-1 px-4 py-2 bg-green-500 hover:bg-green-600 text-white rounded-lg font-bold text-sm"
            >
              Finish Quiz
            </button>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center">
      <div className="bg-white w-full h-full flex flex-col">
        {/* Header */}
        <div className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-6 py-4 flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold">{title}</h2>
            <p className="text-sm text-white/80">{subject} • {materialType.charAt(0).toUpperCase() + materialType.slice(1)}</p>
          </div>
          <button
            onClick={onClose}
            className="w-10 h-10 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center transition-all"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="flex-1 flex overflow-hidden">
          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Content Area */}
            <div className="flex-1 overflow-y-auto bg-gray-50 p-6">
              {materialType === 'video' && (
                <div className="bg-black rounded-lg overflow-hidden">
                  <video
                    ref={videoRef}
                    className="w-full"
                    onTimeUpdate={handleTimeUpdate}
                    onLoadedMetadata={handleLoadedMetadata}
                    src="https://www.w3schools.com/html/mov_bbb.mp4"
                  />
                  <div className="bg-gray-900 p-4">
                    <div className="mb-3">
                      <input
                        type="range"
                        min="0"
                        max={duration || 0}
                        value={currentTime}
                        onChange={(e) => seekTo(parseFloat(e.target.value))}
                        className="w-full"
                      />
                      <div className="flex justify-between text-white text-sm mt-1">
                        <span>{formatTime(currentTime)}</span>
                        <span>{formatTime(duration)}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <button
                        onClick={() => skip(-10)}
                        className="text-white hover:text-purple-400"
                      >
                        <SkipBack className="w-5 h-5" />
                      </button>
                      <button
                        onClick={togglePlayPause}
                        className="w-12 h-12 bg-purple-600 hover:bg-purple-700 rounded-full flex items-center justify-center"
                      >
                        {isPlaying ? <Pause className="w-6 h-6 text-white" /> : <Play className="w-6 h-6 text-white" />}
                      </button>
                      <button
                        onClick={() => skip(10)}
                        className="text-white hover:text-purple-400"
                      >
                        <SkipForward className="w-5 h-5" />
                      </button>
                      <button
                        onClick={toggleMute}
                        className="text-white hover:text-purple-400"
                      >
                        {isMuted ? <VolumeX className="w-5 h-5" /> : <Volume2 className="w-5 h-5" />}
                      </button>
                      <select
                        value={playbackSpeed}
                        onChange={(e) => changeSpeed(parseFloat(e.target.value))}
                        className="bg-gray-800 text-white px-3 py-1 rounded text-sm"
                      >
                        <option value="0.5">0.5x</option>
                        <option value="0.75">0.75x</option>
                        <option value="1">1x</option>
                        <option value="1.25">1.25x</option>
                        <option value="1.5">1.5x</option>
                        <option value="2">2x</option>
                      </select>
                    </div>
                  </div>
                </div>
              )}

              {materialType === 'audio' && (
                <div className="bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg p-8 text-white">
                  <audio
                    ref={audioRef}
                    onTimeUpdate={handleTimeUpdate}
                    onLoadedMetadata={handleLoadedMetadata}
                    src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
                  />
                  <div className="text-center mb-8">
                    <Headphones className="w-24 h-24 mx-auto mb-4" />
                    <h3 className="text-2xl font-bold mb-2">{title}</h3>
                    <p className="text-white/80">Audio Lecture</p>
                  </div>
                  <div className="mb-6">
                    <input
                      type="range"
                      min="0"
                      max={duration || 0}
                      value={currentTime}
                      onChange={(e) => seekTo(parseFloat(e.target.value))}
                      className="w-full"
                    />
                    <div className="flex justify-between text-sm mt-2">
                      <span>{formatTime(currentTime)}</span>
                      <span>{formatTime(duration)}</span>
                    </div>
                  </div>
                  <div className="flex items-center justify-center gap-6">
                    <button
                      onClick={() => skip(-10)}
                      className="text-white hover:text-pink-200"
                    >
                      <SkipBack className="w-6 h-6" />
                    </button>
                    <button
                      onClick={togglePlayPause}
                      className="w-16 h-16 bg-white text-purple-600 hover:bg-pink-100 rounded-full flex items-center justify-center"
                    >
                      {isPlaying ? <Pause className="w-8 h-8" /> : <Play className="w-8 h-8" />}
                    </button>
                    <button
                      onClick={() => skip(10)}
                      className="text-white hover:text-pink-200"
                    >
                      <SkipForward className="w-6 h-6" />
                    </button>
                    <button
                      onClick={toggleMute}
                      className="text-white hover:text-pink-200"
                    >
                      {isMuted ? <VolumeX className="w-6 h-6" /> : <Volume2 className="w-6 h-6" />}
                    </button>
                    <select
                      value={playbackSpeed}
                      onChange={(e) => changeSpeed(parseFloat(e.target.value))}
                      className="bg-white/20 text-white px-4 py-2 rounded"
                    >
                      <option value="0.5">0.5x</option>
                      <option value="0.75">0.75x</option>
                      <option value="1">1x</option>
                      <option value="1.25">1.25x</option>
                      <option value="1.5">1.5x</option>
                      <option value="2">2x</option>
                    </select>
                  </div>
                </div>
              )}

              {materialType === 'notes' && (
                <div className="bg-white rounded-lg shadow-lg p-8 max-w-4xl mx-auto">
                  <div className="prose max-w-none">
                    {notesContent.split('\n\n').map((paragraph, idx) => {
                      if (paragraph.startsWith('# ')) {
                        return <h1 key={idx} className="text-3xl font-bold text-gray-900 mb-4">{paragraph.slice(2)}</h1>;
                      } else if (paragraph.startsWith('## ')) {
                        return <h2 key={idx} className="text-2xl font-bold text-gray-800 mt-6 mb-3">{paragraph.slice(3)}</h2>;
                      } else if (paragraph.startsWith('### ')) {
                        return <h3 key={idx} className="text-xl font-bold text-gray-700 mt-4 mb-2">{paragraph.slice(4)}</h3>;
                      } else if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
                        return <p key={idx} className="font-bold text-gray-900 my-2">{paragraph.slice(2, -2)}</p>;
                      } else if (paragraph.startsWith('`') && paragraph.endsWith('`')) {
                        return <code key={idx} className="block bg-gray-100 p-3 rounded my-2 font-mono text-sm">{paragraph.slice(1, -1)}</code>;
                      } else if (paragraph.match(/^[0-9]\./)) {
                        return <li key={idx} className="ml-6 my-1 text-gray-700">{paragraph.slice(3)}</li>;
                      } else if (paragraph.startsWith('- ') || paragraph.startsWith('• ')) {
                        return <li key={idx} className="ml-6 my-1 text-gray-700">{paragraph.slice(2)}</li>;
                      } else {
                        return <p key={idx} className="text-gray-700 my-3 leading-relaxed">{paragraph}</p>;
                      }
                    })}
                  </div>
                </div>
              )}

              {/* Annotations Display */}
              {showAnnotations && annotations.length > 0 && (
                <div className="mt-6 bg-yellow-50 rounded-lg p-4 border-2 border-yellow-200">
                  <h4 className="text-sm font-bold text-yellow-900 mb-3 flex items-center gap-2">
                    <Highlighter className="w-4 h-4" />
                    Your Annotations ({annotations.length})
                  </h4>
                  <div className="space-y-2">
                    {annotations.map(ann => (
                      <div key={ann.id} className="bg-white p-3 rounded border border-yellow-300">
                        <div className="flex items-start justify-between">
                          <div className="flex-1">
                            <p className="text-sm font-bold text-gray-800">{ann.text}</p>
                            {ann.timestamp !== undefined && (
                              <p className="text-xs text-gray-600 mt-1">At {formatTime(ann.timestamp)}</p>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Quick Actions Bar */}
            {showQuickActions && (
              <div className="bg-white border-t border-gray-200 px-6 py-3">
                <div className="flex items-center gap-2 overflow-x-auto">
                  <button
                    onClick={() => handleQuickAction('Explain this concept in simple terms')}
                    className="px-4 py-2 bg-purple-50 hover:bg-purple-100 text-purple-700 rounded-full text-sm font-bold whitespace-nowrap flex items-center gap-2"
                  >
                    <Lightbulb className="w-4 h-4" />
                    Explain Concept
                  </button>
                  <button
                    onClick={() => handleQuickAction('Give me a practice problem')}
                    className="px-4 py-2 bg-blue-50 hover:bg-blue-100 text-blue-700 rounded-full text-sm font-bold whitespace-nowrap flex items-center gap-2"
                  >
                    <FileQuestion className="w-4 h-4" />
                    Practice Problem
                  </button>
                  <button
                    onClick={() => handleQuickAction('Summarize what I just learned')}
                    className="px-4 py-2 bg-green-50 hover:bg-green-100 text-green-700 rounded-full text-sm font-bold whitespace-nowrap flex items-center gap-2"
                  >
                    <ListChecks className="w-4 h-4" />
                    Summarize
                  </button>
                  <button
                    onClick={() => setShowQuiz(true)}
                    className="px-4 py-2 bg-orange-50 hover:bg-orange-100 text-orange-700 rounded-full text-sm font-bold whitespace-nowrap flex items-center gap-2"
                  >
                    <Trophy className="w-4 h-4" />
                    Take Quiz
                  </button>
                  <button
                    onClick={() => handleQuickAction('Create a mind map of key concepts')}
                    className="px-4 py-2 bg-pink-50 hover:bg-pink-100 text-pink-700 rounded-full text-sm font-bold whitespace-nowrap flex items-center gap-2"
                  >
                    <Map className="w-4 h-4" />
                    Mind Map
                  </button>
                  <button
                    onClick={addAnnotation}
                    className="px-4 py-2 bg-yellow-50 hover:bg-yellow-100 text-yellow-700 rounded-full text-sm font-bold whitespace-nowrap flex items-center gap-2"
                  >
                    <Highlighter className="w-4 h-4" />
                    Add Note
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* AI Tutor Sidebar */}
          {showAITutor && (
            <div className="w-96 bg-white border-l border-gray-200 flex flex-col">
              <div className="bg-gradient-to-r from-purple-500 to-pink-500 text-white px-4 py-3 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Brain className="w-5 h-5" />
                  <div>
                    <h3 className="font-bold text-sm">AI Study Tutor</h3>
                    <p className="text-xs text-white/80">Ask anything!</p>
                  </div>
                </div>
                <button
                  onClick={() => setShowAITutor(false)}
                  className="text-white/80 hover:text-white"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {showQuiz ? (
                <div className="flex-1 overflow-y-auto p-4">
                  {renderQuiz()}
                </div>
              ) : (
                <>
                  <div className="flex-1 overflow-y-auto p-4 space-y-3">
                    {chatMessages.map(message => (
                      <div
                        key={message.id}
                        className={`flex gap-2 ${message.role === 'student' ? 'justify-end' : 'justify-start'}`}
                      >
                        {message.role === 'ai' && (
                          <div className="w-8 h-8 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center flex-shrink-0">
                            <Brain className="w-4 h-4 text-white" />
                          </div>
                        )}
                        <div
                          className={`max-w-[80%] rounded-lg p-3 ${
                            message.role === 'student'
                              ? 'bg-purple-500 text-white'
                              : 'bg-gray-100 text-gray-800'
                          }`}
                        >
                          <div className="text-xs whitespace-pre-line">{message.content}</div>
                          <div className={`text-[9px] mt-1 ${
                            message.role === 'student' ? 'text-white/70' : 'text-gray-500'
                          }`}>
                            {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                            {message.context && ` • ${message.context}`}
                          </div>
                        </div>
                        {message.role === 'student' && (
                          <div className="w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center flex-shrink-0">
                            <span className="text-sm">👤</span>
                          </div>
                        )}
                      </div>
                    ))}
                    {isTyping && (
                      <div className="flex gap-2 justify-start">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center flex-shrink-0">
                          <Brain className="w-4 h-4 text-white" />
                        </div>
                        <div className="bg-gray-100 rounded-lg p-3">
                          <div className="flex gap-1">
                            <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                            <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                            <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                          </div>
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>

                  <div className="p-4 border-t border-gray-200">
                    <div className="flex gap-2">
                      <input
                        type="text"
                        value={chatInput}
                        onChange={(e) => setChatInput(e.target.value)}
                        onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                        placeholder="Ask a question..."
                        className="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm"
                      />
                      <button
                        onClick={handleSendMessage}
                        disabled={!chatInput.trim()}
                        className="px-4 py-2 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 disabled:from-gray-400 disabled:to-gray-400 disabled:cursor-not-allowed text-white rounded-lg font-bold"
                      >
                        <Send className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </>
              )}
            </div>
          )}
        </div>

        {/* Floating AI Button when sidebar is closed */}
        {!showAITutor && (
          <button
            onClick={() => setShowAITutor(true)}
            className="fixed bottom-6 right-6 w-16 h-16 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white rounded-full shadow-2xl flex items-center justify-center animate-pulse"
          >
            <Brain className="w-8 h-8" />
          </button>
        )}
      </div>
    </div>
  );
}
